// Voice Lines Array
const asheVoiceLines = [
    "Dynamite out.", 
    "Fire in the hole!", 
    "Here it comes!", 
    "Hey! Catch!", 
    "She's gonna blow!", 
    "Smoke 'em outta there.", 
    "Dy-Nano-mite out!", 
    "Bob! Do somethin'!", 
    "Get in there, Bob.", 
    "Attaboy, Bob!",	
    "Bob, get out of there!",
    "Enough, Bob.",	
    "Good shootin', Bob.",	
    "I can always count on you, Bob.",
    "Thanks, Bob.",
    "Bob, I have HAD IT with you!",	
    "Dang it, Bob!",	
    "Step it up, Bob!",
    "Not again...",
    "They got Bob! Dammit.",	
    "Well, that's just grand.",	
    "*frustrated grunt* You'll pay for that!"
];
const dvaVoiceLines = [
    "Forward barrier activated!",
    "Initiating defense matrix!",
    "Neutralizing projectiles!",
    "Nothing gets past me!",
    "Eolimdo eobsji!",
    "Usgigo issne!",
    "*yawns* Boring!",
    "Don't think so!",
    "Excuse you!",
    "Oops! Was that your best?",	
    "*laughs* Bang-geum geon mian!",
    "Diving in!",
    "Engaging thrusters!",
    "Flying high!",
    "Mobilizing!",
    "Speeding up!",
    "Dallyeo!",
    "Nerf this! (self and hostile)",
    "Activating self-destruct sequence! (allies)",
    "Booting up!",
    "C'mere, Tokki!",
    "Calling in the big guns!",
    "Initializing systems!",
    "New mech, new me!",
    "Kkangchong, kkangchong!",
    "D.Va back in action!",
    "Game on!",
    "Let's mech up this party!",
    "Miss me?",
    "Sago chil junbi doen salam?",
    "Gotta bail!",
    "I'm out!",
    "Pilot disengaging!",
    "Tokki compromised!"
];
const lifeweaverVoiceLines = [
    "A little care always helps.",
    "A touch of regrowth.",
    "Better?",
    "Better than new!",
    "Can't have it getting worse.",
    "Feeling better, I hope.",
    "Let's perk you up.",
    "Let's put something on that.",
    "Life from life.",
    "Some healing?",
    "Something for the sting.",
    "That should do it.",
    "The warmth of biolight.",
    "You're blossoming!",
    "Climb aboard!",
    "Hop on!",
    "Flowers lift the spirit.",
    "Need a lift?",
    "The air calls.",
    "Time for spring!",
    "Up and at 'em!",
    "Bounding forth.",
    "In the flow.",
    "Irrepressible.",
    "Windborne.",
    "Lâwng bpai gàp sǎai-lom.",
    "Come here, will you?",
    "I have you.",
    "Safety in numbers!",
    "Stay near, hm?",
    "You're better off with me.",
    "A big hug for a large friend.",
    "There, we can protect each other now.",
    "Life protects life!",
    "Chii-wít bpòk-bpâawng chii-wít!"
];

export { asheVoiceLines, dvaVoiceLines, lifeweaverVoiceLines }